const SDK={
permissions:["app.background_keep_alive","app.info.read","app.open_url","app.run_on_startup","app.shortcuts","app.startup_contributions","app.user_email.read","bookmarks.read","bookmarks.write","calendar.read","clipboard.read","database.read","feedback.send_email","fonts.local.read","fs.folder_access","fs.user_files.read","fs.user_files.write","history.read","history.write","library.books.read","library.content.read","library.links.read","library.refresh","navigation.write","network.access","network.localhost","notes.read","notes.write","notifications.send","notifications.system","plugin.open_other","plugin.storage.read","plugin.storage.write","published_data.write","reader.context_menu","reader.highlight","reader.open","reader.toolbar","search.dialog","search.fulltext.read","settings.read","tools.read","ui.create_shortcut","ui.feedback","workspace.manage","workspace.read"],
methods:["app.getInfo","app.getTheme","app.getLocale","app.getGrantedPermissions","app.registerShortcut","library.findBooks","library.getBookContent","library.getTree","library.getLinks","reader.getCurrentState","reader.getSelection","reader.openBook","reader.addContextMenuItem","reader.addToolbarItem","reader.setHighlight","search.fullText","search.query","storage.get","storage.set","ui.showMessage","ui.showConfirm","workspace.list","workspace.create","bookmarks.list","notes.list","history.list","tools.dictionary","tools.gematria","database.query","plugin.listInstalled","plugin.openSelf","plugin.openOther","fs.pickUserFile","fs.pickUserFolder","network.fetchStream"]
};
const KEY="otzaria-plugin-studio-v01";
const starter={
"manifest.json":JSON.stringify({schemaVersion:1,id:"my-plugin",name:"My Plugin",version:"0.1.0",description:"",author:"",homepage:"",entrypoint:"index.html",minAppVersion:"0.9.98",sdkVersion:"1.x",stability:"experimental",permissions:[],network:{enabled:false,allowlist:[]},contributes:{toolTab:{title:"My Plugin",order:900,defaultPinned:true},publishedDataTypes:[],databaseSources:[]}},null,2),
"index.html":`<!doctype html>\n<html lang="he" dir="rtl">\n<head><meta charset="utf-8"><link rel="stylesheet" href="style.css"></head>\n<body>\n  <h1>התוסף הראשון שלי</h1>\n  <button id="hello">בדיקה</button>\n  <script src="main.js"><\/script>\n</body>\n</html>`,
"style.css":"body { font-family: sans-serif; padding: 24px; }\n",
"main.js":"document.querySelector('#hello').addEventListener('click', () => {\n  console.log('Plugin ready');\n});\n"
};
let state=load(), current=Object.keys(state.files)[0], open=[current];
const $=s=>document.querySelector(s), editor=$("#editor");
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{name:"My Plugin",files:{...starter}}}catch{return{name:"My Plugin",files:{...starter}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$("#statusText").textContent="נשמר";setTimeout(()=>$("#statusText").textContent="מוכן",700)}
function esc(s){return s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function renderFiles(){$("#projectName").textContent="▾ "+state.name;$("#fileTree").innerHTML=Object.keys(state.files).sort().map(f=>`<div class="file ${f===current?"active":""}" data-file="${esc(f)}">📄 ${esc(f)}</div>`).join("");document.querySelectorAll(".file").forEach(x=>x.onclick=()=>openFile(x.dataset.file))}
function renderTabs(){$("#tabs").innerHTML=open.map(f=>`<button class="tab ${f===current?"active":""}" data-file="${esc(f)}">${esc(f)}</button>`).join("");document.querySelectorAll(".tab").forEach(x=>x.onclick=()=>openFile(x.dataset.file))}
function openFile(f){if(!state.files.hasOwnProperty(f))return;current=f;if(!open.includes(f))open.push(f);editor.value=state.files[f];renderFiles();renderTabs();lines();cursor()}
function lines(){const n=Math.max(1,editor.value.split("\n").length);$("#lineNumbers").textContent=Array.from({length:n},(_,i)=>i+1).join("\n")}
function cursor(){const p=editor.selectionStart,b=editor.value.slice(0,p),a=b.split("\n");$("#cursor").textContent=`Ln ${a.length}, Col ${a.at(-1).length+1}`}
editor.addEventListener("input",()=>{state.files[current]=editor.value;lines();save();validate()});editor.addEventListener("keyup",cursor);editor.addEventListener("click",cursor);editor.addEventListener("scroll",()=>$("#lineNumbers").scrollTop=editor.scrollTop);
editor.addEventListener("keydown",e=>{if(e.key==="Tab"){e.preventDefault();const s=editor.selectionStart;editor.setRangeText("  ",s,editor.selectionEnd,"end");editor.dispatchEvent(new Event("input"))}if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();save();log("Project saved","ok")}});
$("#addFile").onclick=()=>{const n=prompt("שם הקובץ החדש:","new-file.js");if(!n||state.files[n]!=null)return;state.files[n]="";openFile(n);save()};
$("#renameFile").onclick=()=>{const n=prompt("שם חדש:",current);if(!n||n===current||state.files[n]!=null)return;state.files[n]=state.files[current];delete state.files[current];open=open.map(x=>x===current?n:x);current=n;openFile(n);save()};
$("#deleteFile").onclick=()=>{if(Object.keys(state.files).length===1||!confirm(`למחוק את ${current}?`))return;delete state.files[current];open=open.filter(x=>x!==current);current=Object.keys(state.files)[0];if(!open.includes(current))open.push(current);openFile(current);save()};
$("#newProject").onclick=()=>{if(!confirm("ליצור פרויקט חדש? הפרויקט הנוכחי יוחלף."))return;const n=prompt("שם הפרויקט:","New Plugin")||"New Plugin";state={name:n,files:{...starter}};current="manifest.json";open=[current];save();openFile(current);log("New project created","ok")};
function log(msg,type=""){const d=document.createElement("div");d.innerHTML=`<span class="log-time">[${new Date().toLocaleTimeString()}]</span> <span class="${type==="ok"?"log-ok":type==="warn"?"log-warn":""}">${esc(msg)}</span>`;$("#consolePanel").appendChild(d);$("#consolePanel").scrollTop=99999}
function showPanel(name){document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));document.querySelectorAll(".bottom-tabs button").forEach(x=>x.classList.remove("active"));$("#"+name+"Panel").classList.remove("hidden");document.querySelector(`[data-panel="${name}"]`).classList.add("active")}
document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));
$("#runPreview").onclick=()=>{const h=state.files["index.html"];if(!h){log("index.html לא נמצא","warn");return}let doc=h.replace(/<link[^>]+href=["']([^"']+)["'][^>]*>/gi,(_,f)=>state.files[f]?`<style>${state.files[f]}</style>`:"").replace(/<script[^>]+src=["']([^"']+)["'][^>]*><\/script>/gi,(_,f)=>state.files[f]?`<script>${state.files[f]}<\/script>`:"");$("#previewPanel").srcdoc=doc;showPanel("preview");log("Preview refreshed","ok")};
let sdkMode="methods";function renderSdk(){const q=$("#sdkSearch").value.toLowerCase(),arr=SDK[sdkMode].filter(x=>x.toLowerCase().includes(q));$("#sdkList").innerHTML=arr.map(x=>`<div class="sdk-item" data-value="${x}">${x}<small>${sdkMode==="methods"?"API method":"manifest permission"}</small></div>`).join("")||'<div class="empty">אין תוצאות</div>';document.querySelectorAll(".sdk-item").forEach(x=>x.onclick=()=>{const v=x.dataset.value;editor.setRangeText(v,editor.selectionStart,editor.selectionEnd,"end");editor.dispatchEvent(new Event("input"));editor.focus()})}
$("#sdkSearch").oninput=renderSdk;document.querySelectorAll("[data-sdk]").forEach(b=>b.onclick=()=>{sdkMode=b.dataset.sdk;document.querySelectorAll("[data-sdk]").forEach(x=>x.classList.toggle("active",x===b));renderSdk()});
function validate(){const p=[];if(state.files["manifest.json"]){try{const m=JSON.parse(state.files["manifest.json"]);["id","name","version","entrypoint"].forEach(k=>{if(!m[k])p.push("manifest: missing "+k)});(m.permissions||[]).forEach(x=>{if(!SDK.permissions.includes(x))p.push("Unknown permission: "+x)})}catch(e){p.push("manifest.json: "+e.message)}}else p.push("manifest.json is missing");$("#problemsPanel").innerHTML=p.length?p.map(x=>`<div>⚠ ${esc(x)}</div>`).join(""):'<div class="log-ok">✓ לא נמצאו בעיות בסיסיות</div>'}
renderFiles();renderTabs();openFile(current);renderSdk();validate();log("Plugin Studio 0.1 initialized","ok");