(()=>{
const $=q=>document.querySelector(q),A=window.PluginStudioAPI;if(!A)throw Error("Diagnostics: API unavailable");
let last=[];function versionGt(a,b){const A=String(a||"0").split(".").map(x=>parseInt(x)||0),B=String(b||"0").split(".").map(x=>parseInt(x)||0);for(let i=0;i<Math.max(A.length,B.length,3);i++){if((A[i]||0)!==(B[i]||0))return (A[i]||0)>(B[i]||0)}return false}
function scan(){const out=[],spec=window.OTZARIA_SDK_SPEC||{},files=A.state.files;let manifest;try{manifest=JSON.parse(files["manifest.json"]||"");}catch(e){out.push({level:"error",file:"manifest.json",line:1,msg:"manifest.json אינו JSON תקין: "+e.message});return out}
for(const k of ["id","name","version","entrypoint"])if(!manifest[k])out.push({level:"error",file:"manifest.json",line:1,msg:"חסר שדה manifest: "+k});
if(manifest.entrypoint&&!files[manifest.entrypoint])out.push({level:"error",file:"manifest.json",line:1,msg:"entrypoint לא נמצא: "+manifest.entrypoint});
if(manifest.network?.enabled)out.push({level:"error",file:"manifest.json",line:1,msg:"Plugin Studio מוגדר Offline-only: network.enabled אסור"});
const declared=new Set([...(manifest.permissions||[]),...(spec.baselinePermissions||[])]);
for(const [name,code] of Object.entries(files)){if(!/\.(js|html)$/.test(name))continue;const lines=code.split("\n");lines.forEach((line,i)=>{for(const m of line.matchAll(/Otzaria\.call\(\s*["']([^"']+)["']/g)){const api=m[1];if(!spec.apiMethods?.includes(api)){out.push({level:"error",file:name,line:i+1,msg:"API לא מוכר: "+api});continue}const p=spec.methodPermissions?.[api];if(p&&p!=="baseline"&&!declared.has(p))out.push({level:"warning",file:name,line:i+1,msg:"חסרה הרשאה "+p+" עבור "+api,fix:{type:"permission",value:p}});const min=spec.methodMinVersions?.[api];if(min&&manifest.minAppVersion&&versionGt(min,manifest.minAppVersion))out.push({level:"warning",file:name,line:i+1,msg:api+" דורש Otzaria ≥ "+min,fix:{type:"minVersion",value:min}})}});if(/https?:\/\//i.test(code))out.push({level:"error",file:name,line:1,msg:"נמצאה כתובת רשת בפרויקט Offline-only"})}
try{out.push(...(window.Intelligence4?.diagnostics?.()||[]))}catch{}return out}
function applyFix(p){let m=JSON.parse(A.state.files["manifest.json"]);if(p.fix?.type==="permission"){m.permissions=[...new Set([...(m.permissions||[]),p.fix.value])].sort()}else if(p.fix?.type==="minVersion"){m.minAppVersion=p.fix.value}else return;A.state.files["manifest.json"]=JSON.stringify(m,null,2);A.save();run()}
function run(){last=scan();A.dialog("Diagnostics 3.0",'<div class="notice">'+(last.length?last.length+" ממצאים":"✓ לא נמצאו בעיות בבדיקות המקומיות")+'</div><div id="diagList">'+last.map((p,i)=>'<div class="card"><div><b class="'+p.level+'">'+p.level.toUpperCase()+'</b> <span dir="ltr">'+A.escapeHtml(p.file+":"+p.line)+'</span><br><small>'+A.escapeHtml(p.msg)+'</small></div><div><button data-go="'+i+'">פתח</button>'+(p.fix?'<button data-fix="'+i+'">Quick Fix</button>':'')+'</div></div>').join("")+'</div>');document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{const p=last[+b.dataset.go];$("#dlg").close();window.EditorAdvanced?.goto(p.file,p.line)});document.querySelectorAll("[data-fix]").forEach(b=>b.onclick=()=>applyFix(last[+b.dataset.fix]))}
$("#diagnosticsBtn").onclick=run;window.Diagnostics3={scan,run};setInterval(()=>{last=scan();const n=last.filter(x=>x.level==="error").length,w=last.filter(x=>x.level==="warning").length;if($("#status")){$("#status").dataset.diagnostics=n+" errors · "+w+" warnings";$("#status").title=n+" errors · "+w+" warnings"}},2500);
})();