(()=>{const A=window.PluginStudioAPI,$=q=>document.querySelector(q);if(!A)return;
const cm=()=>window.StudioCodeMirror;
function token(){const c=cm();if(!c)return"";const p=c.getCursor(),l=c.getLine(p.line),m=l.slice(0,p.ch).match(/[A-Za-z_$][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)*$/);return m?m[0]:""}
function hints(){const c=cm();if(!c||!window.CodeMirror||!CodeMirror.showHint)return;const p=c.getCursor(),q=token(),from={line:p.line,ch:p.ch-q.length},list=(A.sdk.methods||[]).filter(x=>!x.startsWith("network.")&&(!q||x.toLowerCase().includes(q.toLowerCase()))).slice(0,100).map(x=>({text:x,displayText:x+" · "+(A.sdk.methodPermissions?.[x]||"baseline")}));CodeMirror.showHint(c,()=>({from:from,to:p,list:list}),{completeSingle:false})}
function signature(){const q=token(),n=(A.sdk.methods||[]).find(x=>q.endsWith(x));if(!n)return;$("#status").textContent=((window.OTZARIA_SIGNATURES||{})[n]||n+"(args)")+" · "+(A.sdk.methodPermissions?.[n]||"baseline")+" · min "+(A.sdk.methodMinVersions?.[n]||"?")}
function gotoDef(){const c=cm(),w=token().split(".").pop();if(!c||!w)return;for(const pair of Object.entries(A.state.files)){const name=pair[0],lines=pair[1].split("\n");const i=lines.findIndex(x=>x.includes("function "+w)||x.includes("const "+w)||x.includes("let "+w)||x.includes("class "+w));if(i>=0){A.openFile(name);setTimeout(()=>{const e=cm();if(e){e.setCursor({line:i,ch:0});e.focus()}},0);return}}alert("לא נמצאה הגדרה מקומית עבור "+w)}
function rename(){const w=token().split(".").pop();if(!w)return;const n=prompt("שם חדש:",w);if(!n||n===w||!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n))return;A.snapshot(true,"Before rename "+w);const re=new RegExp("\\b"+w.replace(/[.*+?^$()|[\\]{}\\\\]/g,"\\for(const k in A.state.files)if(/\.(js|html|css|json)$/.test(k))A.state.files[k]=A.state.files[k].split(w).join(n);A.save();A.openFile(A.currentFile)")+"\\b","g");for(const k in A.state.files)if(/\.(js|html|css|json)$/.test(k))A.state.files[k]=A.state.files[k].replace(re,n);A.save();A.openFile(A.currentFile)}
function markers(){const c=cm();if(!c)return;let d=[];try{d=window.Diagnostics3?.scan?.()||[]}catch{}c.clearGutter("audit-errors");c.setOption("gutters",["CodeMirror-linenumbers","CodeMirror-foldgutter","audit-errors"]);for(const x of d){if(x.file!==A.currentFile||!Number.isInteger(x.line))continue;const m=document.createElement("span");m.textContent=x.level==="error"?"●":"▲";m.className="cmDiag "+x.level;m.title=x.message||x.text||"";c.setGutterMarker(Math.max(0,x.line-1),"audit-errors",m)}}
function install(){const c=cm();if(!c)return setTimeout(install,80);c.addKeyMap({"Ctrl-Space":hints,"F12":gotoDef,"F2":rename});c.on("cursorActivity",signature);document.addEventListener("pluginstudio:file-opened",()=>setTimeout(markers,0));setInterval(markers,3500);markers()}
install();window.EditorPro={hints,signature,gotoDef,rename,markers}})();
