(()=>{const A=window.PluginStudioAPI;const K="plugin-studio-language-v1";
const he={develop:"פיתוח",design:"עיצוב",test:"בדיקות",debug:"ניפוי שגיאות",release:"הפצה",openTool:"פתח כלי",projects:"פרויקטים",pluginGenerator:"מחולל תוספים",templates:"תבניות",projectSearch:"חיפוש בפרויקט",commands:"פקודות",apiLab:"מעבדת API",workflowBuilder:"בונה תהליכים",visualBuilder:"בונה חזותי",manifestDesigner:"עורך Manifest",themePreview:"ערכת נושא ותצוגה",sdkExplorer:"סייר SDK",testingStudio:"מרכז בדיקות",diagnostics:"אבחון",pluginDoctor:"רופא התוסף",build:"בנייה",simulator:"מדמה Otzaria",testRecorder:"מקליט בדיקות",debugInspector:"מפקח ניפוי שגיאות",events:"אירועים",versions:"גרסאות",devTools:"כלי פיתוח",releaseCenter:"מרכז הפצה",releaseWizard:"אשף הפצה",packageCenter:"מרכז אריזה",exportProject:"ייצוא פרויקט",permissions:"הרשאות",localHistory:"היסטוריה מקומית",language:"שפה",automatic:"אוטומטי",hebrew:"עברית",english:"אנגלית",settings:"הגדרות",offline:"לא מקוון",preview:"תצוגה",more:"עוד",newProject:"חדש",openPlugin:"פתח תוסף"};
const en={develop:"Develop",design:"Design",test:"Test",debug:"Debug",release:"Release",openTool:"Open tool",projects:"Projects",pluginGenerator:"Plugin Generator",templates:"Templates",projectSearch:"Project Search",commands:"Commands",apiLab:"API Lab",workflowBuilder:"Workflow Builder",visualBuilder:"Visual Builder",manifestDesigner:"Manifest Designer",themePreview:"Theme & Preview",sdkExplorer:"SDK Explorer",testingStudio:"Testing Studio",diagnostics:"Diagnostics",pluginDoctor:"Plugin Doctor",build:"Build",simulator:"Otzaria Simulator",testRecorder:"Test Recorder",debugInspector:"Debug Inspector",events:"Events",versions:"Versions",devTools:"Developer Tools",releaseCenter:"Release Center",releaseWizard:"Release Wizard",packageCenter:"Package Center",exportProject:"Export Project",permissions:"Permissions",localHistory:"Local History",language:"Language",automatic:"Automatic",hebrew:"Hebrew",english:"English",settings:"Settings",offline:"OFFLINE",preview:"Preview",more:"More",newProject:"New",openPlugin:"Open Plugin"};
let mode=localStorage.getItem(K)||"auto",locale="he";
function normalize(x){return String(x||"").toLowerCase().startsWith("he")?"he":"en"}async function detect(){if(mode!=="auto"){locale=mode;apply();return}try{const x=await (A.callLogged||A.hostCall)?.("app.getLocale",{});locale=normalize(typeof x==="string"?x:x?.locale)}catch{locale=normalize(document.documentElement.lang||navigator.language)}apply()}
function t(k){return (locale==="he"?he:en)[k]||en[k]||k}function setMode(x){mode=["auto","he","en"].includes(x)?x:"auto";localStorage.setItem(K,mode);detect()}
function apply(){document.documentElement.lang=locale;document.documentElement.dir=locale==="he"?"rtl":"ltr";document.body.classList.toggle("langLtr",locale==="en");const map={projects:"projects",newProject:"newProject",importPackage:"openPlugin",preview:"preview",buildBtn:"build",moreToolsBtn:"more",studioSettingsBtn:"settings",pluginGeneratorBtn:"pluginGenerator",testingStudioBtn:"testingStudio",releaseProBtn:"releaseCenter",permissionAssistantBtn:"permissions",timelineBtn:"localHistory",simulatorBtn:"simulator",workflowBuilderBtn:"workflowBuilder",testRecorderBtn:"testRecorder"};for(const [id,k] of Object.entries(map)){const e=document.getElementById(id);if(e)e.textContent=t(k)}document.querySelectorAll(".studioSections [data-section]").forEach(b=>b.textContent=t(b.dataset.section));document.dispatchEvent(new CustomEvent("pluginstudio:language-changed",{detail:{locale,mode}}))}
function chooser(){A.dialog(t("language"),'<label>'+t("language")+' <select id="langChoice"><option value="auto">'+t("automatic")+'</option><option value="he">'+t("hebrew")+'</option><option value="en">'+t("english")+'</option></select></label>');const s=document.querySelector("#langChoice");s.value=mode;s.onchange=()=>setMode(s.value)}
detect();window.StudioI18n={t,setMode,detect,chooser,get locale(){return locale},get mode(){return mode}}})();
