(()=>{const A=window.PluginStudioAPI,$=q=>document.querySelector(q);if(!A)return;
const he=()=>window.StudioI18n?.locale!=="en",tr=(a,b)=>he()?a:b,cm=()=>window.StudioCodeMirror||null,ident=s=>/^[A-Za-z_$][\w$]*$/.test(s);
function masked(s){return window.SymbolIndex?.masked?.(s)||s.replace(/(["'`])(?:\\.|(?!\1)[\s\S])*?\1/g,m=>" ".repeat(m.length)).replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g,m=>m.replace(/[^\n]/g," "))}
function wordAt(file,index){const s=A.state.files[file]||"",l=s.slice(0,index).match(/[A-Za-z_$][\w$]*$/),r=s.slice(index).match(/^[A-Za-z0-9_$]*/);return(l?.[0]||"")+(r?.[0]||"")}
function scopeDepth(s,pos){let d=0;for(const c of masked(s.slice(0,pos))){if(c==="{")d++;else if(c==="}")d=Math.max(0,d-1)}return d}
function pos(src,index){const before=src.slice(0,index);return{line:before.split("\n").length,col:index-before.lastIndexOf("\n")}}
function resolvePath(from,spec){if(!spec?.startsWith("."))return null;const base=from.split("/");base.pop();for(const p of spec.split("/")){if(p==="."||!p)continue;if(p==="..")base.pop();else base.push(p)}let x=base.join("/");for(const q of [x,x+".js",x+"/index.js"])if(A.state.files[q]!=null)return q;return null}
function imports(file){const src=A.state.files[file]||"",out=[];for(const m of src.matchAll(/\bimport\s+([\s\S]*?)\s+from\s+["']([^"']+)["']/g)){const target=resolvePath(file,m[2]);if(!target)continue;const clause=m[1].trim();if(clause.startsWith("{"))for(const n of clause.slice(1,-1).split(",")){const [orig,local]=n.trim().split(/\s+as\s+/);if(orig)out.push({local:local||orig,original:orig,target})}else if(clause.startsWith("*")){const n=clause.match(/\bas\s+([\w$]+)/)?.[1];if(n)out.push({local:n,original:"*",target})}else{const n=clause.split(",")[0].trim();if(n)out.push({local:n,original:"default",target})}}return out}
function defs(name){const out=[];if(!ident(name))return out;const esc=name.replace(/[$]/g,"\\$&");for(const [file,src] of Object.entries(A.state.files)){if(!/\.(js|html)$/i.test(file))continue;const clean=masked(src),re=new RegExp("\\b(function|class|const|let|var)\\s+"+esc+"\\b","g");let m;while((m=re.exec(clean))){const p=pos(src,m.index);out.push({file,index:m.index,...p,depth:scopeDepth(src,m.index),kind:m[1]})}for(const m of src.matchAll(/\bexport\s*\{([^}]+)\}/g)){for(const n of m[1].split(",")){const [orig,alias]=n.trim().split(/\s+as\s+/);if((alias||orig)===name||orig===name){const i=m.index+m[0].indexOf(orig),p=pos(src,i);out.push({file,index:i,...p,depth:0,kind:"export"})}}}}return out}
function importedTarget(x){const im=imports(x.file).find(i=>i.local===x.name);if(!im)return null;const src=A.state.files[im.target]||"";if(im.original==="default"){const m=src.match(/\bexport\s+default\s+(?:async\s+)?(?:function|class)?\s*([A-Za-z_$][\w$]*)?/);if(m){const i=m.index,p=pos(src,i);return{file:im.target,index:i,...p,depth:0,kind:"export-default"}}}const ds=defs(im.original);return ds.find(d=>d.file===im.target)||null}
function refs(name){const out=[];if(!ident(name))return out;const re=new RegExp("\\b"+name.replace(/[$]/g,"\\$&")+"\\b","g");for(const [file,src] of Object.entries(A.state.files)){if(!/\.(js|html)$/i.test(file))continue;const clean=masked(src);let m;while((m=re.exec(clean))){const p=pos(src,m.index);out.push({file,index:m.index,...p,depth:scopeDepth(src,m.index),text:(src.split("\n")[p.line-1]||"").trim()})}}return out}
function current(){const c=cm();if(!c)return null;const i=c.indexFromPos(c.getCursor()),name=wordAt(A.currentFile,i);return name?{file:A.currentFile,index:i,name,depth:scopeDepth(A.state.files[A.currentFile]||"",i)}:null}
function target(x=current()){if(!x)return null;const imp=importedTarget(x);if(imp)return imp;const ds=defs(x.name),same=ds.filter(d=>d.file===x.file&&d.index<=x.index&&d.depth<=x.depth).sort((a,b)=>(b.depth-a.depth)||(b.index-a.index));return same[0]||ds.find(d=>d.file===x.file)||ds[0]||null}
function goto(d){if(!d)return false;A.openFile(d.file);setTimeout(()=>{const c=cm();c?.setCursor({line:d.line-1,ch:Math.max(0,d.col-1)});c?.focus()},0);return true}
function jump(){return goto(target())}
function scopedRefs(){const x=current(),d=target(x);if(!x||!d)return[];if(d.file!==x.file&&imports(x.file).some(i=>i.local===x.name))return refs(x.name).filter(r=>r.file===x.file);return refs(x.name).filter(r=>r.file===d.file&&r.depth>=d.depth)}
function showRefs(){const x=current(),rs=scopedRefs();if(!x)return false;A.dialog(tr("מופעים: ","References: ")+x.name,rs.length?rs.map(r=>'<button class="symbolRow" data-ref-file="'+A.escapeHtml(r.file)+'" data-ref-line="'+r.line+'"><b>'+A.escapeHtml(r.file+":"+r.line)+'</b><small>'+A.escapeHtml(r.text)+'</small></button>').join(""):'<div class="notice">'+tr("לא נמצאו מופעים","No references")+'</div>');return true}
function applyRename(x,n,rs){A.snapshot?.(true,"Rename "+x.name+" to "+n);const by={};rs.forEach(r=>(by[r.file]??=[]).push(r));for(const [file,a] of Object.entries(by)){let s=A.state.files[file];a.sort((p,q)=>q.index-p.index).forEach(r=>s=s.slice(0,r.index)+n+s.slice(r.index+x.name.length));A.state.files[file]=s}A.save();A.openFile(x.file)}
function rename(){const x=current(),rs=scopedRefs();if(!x||!rs.length)return false;const n=prompt(tr("שם חדש:","New name:"),x.name);if(!n||n===x.name)return true;if(!ident(n))return alert(tr("שם JavaScript אינו תקין","Invalid JavaScript identifier")),true;const rows=rs.map(r=>'<label class="symbolRow"><input type="checkbox" data-rename-ref="'+A.escapeHtml(r.file)+'" data-rename-index="'+r.index+'" checked><span><b>'+A.escapeHtml(r.file+":"+r.line)+'</b><small>'+A.escapeHtml(r.text)+'</small></span></label>').join("");A.dialog(tr("תצוגה מקדימה לשינוי שם","Rename preview"),'<div class="notice">'+A.escapeHtml(x.name+" → "+n)+" · "+rs.length+" "+tr("מופעים","references")+'</div>'+rows+'<button id="renameApply">'+tr("החל שינוי","Apply rename")+'</button>');setTimeout(()=>{$("#renameApply")?.addEventListener("click",()=>{const chosen=[...document.querySelectorAll("[data-rename-ref]:checked")].map(el=>rs.find(r=>r.file===el.dataset.renameRef&&r.index===+el.dataset.renameIndex)).filter(Boolean);if(!chosen.length)return;$("#dlg")?.close();applyRename(x,n,chosen)})},0);return true}
function selected(){const c=cm();if(!c)return null;const s=c.getSelection();if(!s)return null;const a=c.indexFromPos(c.getCursor("from")),b=c.indexFromPos(c.getCursor("to"));return{text:s,start:a,end:b,from:c.getCursor("from"),to:c.getCursor("to")}}
function extractVariable(){const c=cm(),s=selected();if(!c||!s)return false;const n=prompt(tr("שם המשתנה:","Variable name:"),"value");if(!ident(n))return false;const indent=(c.getLine(s.from.line).match(/^\s*/)||[""])[0],decl=indent+"const "+n+" = "+s.text+";\n";A.snapshot?.(true,"Extract variable "+n);c.replaceRange(n,s.from,s.to);c.replaceRange(decl,{line:s.from.line,ch:0});A.state.files[A.currentFile]=c.getValue();A.save();return true}
function extractFunction(){const c=cm(),s=selected();if(!c||!s)return false;const n=prompt(tr("שם הפונקציה:","Function name:"),"extractedFunction");if(!ident(n))return false;const src=c.getValue(),ids=[...new Set([...s.text.matchAll(/\b([A-Za-z_$][\w$]*)\b/g)].map(m=>m[1]))],declared=new Set([...s.text.matchAll(/\b(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/g)].map(m=>m[1])),keywords=new Set(["if","else","for","while","return","const","let","var","function","class","new","true","false","null","undefined","await","async","try","catch","finally","throw","switch","case","break","continue","this"]);const outside=masked(src.slice(0,s.start)+" ".repeat(s.end-s.start)+src.slice(s.end)),params=ids.filter(x=>!declared.has(x)&&!keywords.has(x)&&new RegExp("\\b"+x.replace(/[$]/g,"\\$&")+"\\b").test(outside)).slice(0,12),call=n+"("+params.join(", ")+");",fn="\nfunction "+n+"("+params.join(", ")+"){\n"+s.text.split("\n").map(x=>"  "+x).join("\n")+"\n}\n";A.snapshot?.(true,"Extract function "+n);c.replaceRange(call,s.from,s.to);c.replaceRange(fn,{line:c.lineCount(),ch:0});A.state.files[A.currentFile]=c.getValue();A.save();return true}
function refactorMenu(){const s=selected();if(!s)return false;A.dialog(tr("Refactor בחירה","Refactor selection"),'<div class="notice"><code>'+A.escapeHtml(s.text.slice(0,240))+'</code></div><button id="rfVar">Extract Variable</button> <button id="rfFn">Extract Function</button>');$("#rfVar").onclick=()=>{$("#dlg").close();extractVariable()};$("#rfFn").onclick=()=>{$("#dlg").close();extractFunction()};return true}
function apiArgs(){const c=cm();if(!c)return false;const p=c.getCursor(),before=c.getRange({line:0,ch:0},p),m=before.match(/Otzaria\.call\(\s*["']([^"']+)["']\s*,\s*\{([^{}]*)$/);if(!m)return false;const sig=window.OTZARIA_SIGNATURES?.[m[1]]||"",used=new Set([...m[2].matchAll(/([A-Za-z_$][\w$]*)\s*:/g)].map(x=>x[1])),fields=[...new Set([...sig.matchAll(/\b([A-Za-z_$][\w$]*)\??(?=\s*[,}|])/g)].map(x=>x[1]))].filter(x=>!used.has(x));if(!fields.length)return false;CodeMirror.showHint(c,()=>({from:p,to:p,list:fields.map(x=>({text:x+": ",displayText:x+" · "+m[1]}))}),{completeSingle:false});return true}
function valueHints(){const c=cm();if(!c)return false;const p=c.getCursor(),left=c.getLine(p.line).slice(0,p.ch),m=left.match(/([A-Za-z_$][\w$]*)\s*:\s*["']([^"']*)$/);if(!m)return false;const vals=window.OTZARIA_VALUE_HINTS?.[m[1]]||[];if(!vals.length)return false;return CodeMirror.showHint(c,()=>({from:{line:p.line,ch:p.ch-m[2].length},to:p,list:vals.map(v=>({text:String(v),displayText:String(v)+" · "+m[1]}))}),{completeSingle:false}),true}
function iconCompletion(){const c=cm();if(!c||!window.SymbolLibrary4)return false;const p=c.getCursor(),line=c.getLine(p.line),m=line.slice(0,p.ch).match(/(?:iconName|icon|symbol)\s*[:=]\s*["']([^"']*)$/);if(!m)return false;const q=m[1].toLowerCase(),all=window.SymbolLibrary4.all().filter(x=>x.name.toLowerCase().includes(q)).slice(0,180);CodeMirror.showHint(c,()=>({from:{line:p.line,ch:p.ch-m[1].length},to:p,list:all.map(x=>({text:x.type==="host"?x.hostValue:x.id,displayText:x.name+" · "+x.pack}))}),{completeSingle:false});return true}
function install(){const c=cm();if(!c)return setTimeout(install,100);c.addKeyMap({"F2":rename,"F12":()=>jump()||window.EditorAdvanced?.goToDefinition?.(),"Shift-F12":showRefs,"Ctrl-Shift-R":rename,"Ctrl-Alt-V":extractVariable,"Ctrl-Alt-M":extractFunction,"Ctrl-Space":()=>iconCompletion()||valueHints()||apiArgs()||window.Intelligence4?.completion?.()||window.ManifestIntelliSense&&A.currentFile==="manifest.json"&&window.EditorPro?.hints?.()})}
document.addEventListener("click",e=>{const b=e.target.closest?.("[data-ref-file]");if(!b)return;goto({file:b.dataset.refFile,line:+b.dataset.refLine,col:1,index:0})});
install();window.Intelligence42={current,target,definitions:defs,references:refs,imports,resolvePath,scopedReferences:scopedRefs,goToDefinition:jump,findReferences:showRefs,rename,extractVariable,extractFunction,refactorMenu,apiArgs,valueHints,iconCompletion}})();