(()=>{const A=window.PluginStudioAPI,$=q=>document.querySelector(q);if(!A)return;
const he=()=>window.StudioI18n?.locale!=="en",tr=(a,b)=>he()?a:b,cm=()=>window.StudioCodeMirror||null;
function wordAt(file,index){const s=A.state.files[file]||"",l=s.slice(0,index).match(/[A-Za-z_$][\w$]*$/),r=s.slice(index).match(/^[A-Za-z0-9_$]*/);return(l?.[0]||"")+(r?.[0]||"")}
function masked(s){return window.SymbolIndex?.masked?.(s)||s.replace(/(["'`])(?:\\.|(?!\1)[\s\S])*\1/g,m=>" ".repeat(m.length)).replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g,m=>m.replace(/[^\n]/g," "))}
function scopeDepth(s,pos){let d=0;for(const c of masked(s.slice(0,pos))){if(c==="{")d++;else if(c==="}")d=Math.max(0,d-1)}return d}
function defs(name){const out=[];for(const [file,src] of Object.entries(A.state.files)){if(!/\.(js|html)$/i.test(file))continue;const clean=masked(src),re=new RegExp("\\b(function|class|const|let|var)\\s+"+name.replace(/[$]/g,"\\$&")+"\\b","g");let m;while((m=re.exec(clean))){const before=src.slice(0,m.index),line=before.split("\n").length,col=m.index-before.lastIndexOf("\n");out.push({file,index:m.index,line,col,depth:scopeDepth(src,m.index),kind:m[1]})}}return out}
function refs(name){const out=[];if(!/^[A-Za-z_$][\w$]*$/.test(name))return out;const re=new RegExp("\\b"+name.replace(/[$]/g,"\\$&")+"\\b","g");for(const [file,src] of Object.entries(A.state.files)){if(!/\.(js|html)$/i.test(file))continue;const clean=masked(src);let m;while((m=re.exec(clean))){const before=src.slice(0,m.index);out.push({file,index:m.index,line:before.split("\n").length,col:m.index-before.lastIndexOf("\n"),depth:scopeDepth(src,m.index),text:(src.split("\n")[before.split("\n").length-1]||"").trim()})}}return out}
function current(){const c=cm();if(!c)return null;const i=c.indexFromPos(c.getCursor()),name=wordAt(A.currentFile,i);return name?{file:A.currentFile,index:i,name,depth:scopeDepth(A.state.files[A.currentFile]||"",i)}:null}
function target(x=current()){if(!x)return null;const ds=defs(x.name),same=ds.filter(d=>d.file===x.file&&d.index<=x.index&&d.depth<=x.depth).sort((a,b)=>(b.depth-a.depth)||(b.index-a.index));return same[0]||ds.find(d=>d.file===x.file)||ds[0]||null}
function jump(){const d=target();if(!d)return false;A.openFile(d.file);setTimeout(()=>{const c=cm();c?.setCursor({line:d.line-1,ch:Math.max(0,d.col-1)});c?.focus()},0);return true}
function scopedRefs(){const x=current(),d=target(x);if(!x||!d)return[];return refs(x.name).filter(r=>r.file===d.file&&r.depth>=d.depth)}
function showRefs(){const x=current(),rs=scopedRefs();if(!x)return false;A.dialog(tr("מופעים: ","References: ")+x.name,rs.length?rs.map(r=>'<button class="symbolRow" data-ref-file="'+A.escapeHtml(r.file)+'" data-ref-line="'+r.line+'"><b>'+A.escapeHtml(r.file+":"+r.line)+'</b><small>'+A.escapeHtml(r.text)+'</small></button>').join(""):'<div class="notice">'+tr("לא נמצאו מופעים","No references")+'</div>');return true}
function rename(){const x=current(),rs=scopedRefs();if(!x||!rs.length)return false;const n=prompt(tr("שם חדש:","New name:"),x.name);if(!n||n===x.name)return true;if(!/^[A-Za-z_$][\w$]*$/.test(n))return alert(tr("שם JavaScript אינו תקין","Invalid JavaScript identifier")),true;A.snapshot?.(true,"Rename "+x.name+" to "+n);const by={};rs.forEach(r=>(by[r.file]??=[]).push(r));for(const [file,a] of Object.entries(by)){let s=A.state.files[file];a.sort((p,q)=>q.index-p.index).forEach(r=>s=s.slice(0,r.index)+n+s.slice(r.index+x.name.length));A.state.files[file]=s}A.save();A.openFile(x.file);return true}
function apiArgs(){const c=cm();if(!c)return false;const p=c.getCursor(),before=c.getRange({line:0,ch:0},p),m=before.match(/Otzaria\.call\(\s*["']([^"']+)["']\s*,\s*\{([^{}]*)$/);if(!m)return false;const sig=window.OTZARIA_SIGNATURES?.[m[1]]||"",used=new Set([...m[2].matchAll(/([A-Za-z_$][\w$]*)\s*:/g)].map(x=>x[1])),fields=[...new Set([...sig.matchAll(/\b([A-Za-z_$][\w$]*)\??(?=\s*[,}|])/g)].map(x=>x[1]))].filter(x=>!used.has(x));if(!fields.length)return false;CodeMirror.showHint(c,()=>({from:p,to:p,list:fields.map(x=>({text:x+": ",displayText:x+" · "+m[1]}))}),{completeSingle:false});return true}
function iconCompletion(){const c=cm();if(!c||!window.SymbolLibrary4)return false;const p=c.getCursor(),line=c.getLine(p.line),m=line.slice(0,p.ch).match(/(?:iconName|icon|symbol)\s*[:=]\s*["']([^"']*)$/);if(!m)return false;const q=m[1].toLowerCase(),all=window.SymbolLibrary4.all().filter(x=>x.name.toLowerCase().includes(q)).slice(0,180);CodeMirror.showHint(c,()=>({from:{line:p.line,ch:p.ch-m[1].length},to:p,list:all.map(x=>({text:x.type==="host"?x.hostValue:x.id,displayText:x.name+" · "+x.pack}))}),{completeSingle:false});return true}
function install(){const c=cm();if(!c)return setTimeout(install,100);c.addKeyMap({"F12":()=>jump()||window.EditorAdvanced?.goToDefinition?.(),"Shift-F12":showRefs,"Ctrl-Shift-R":rename,"Ctrl-Space":()=>iconCompletion()||apiArgs()||window.Intelligence4?.completion?.()||window.ManifestIntelliSense&&A.currentFile==="manifest.json"&&window.EditorPro?.hints?.()})}
document.addEventListener("click",e=>{const b=e.target.closest?.("[data-ref-file]");if(!b)return;A.openFile(b.dataset.refFile);$("#dlg")?.close();setTimeout(()=>cm()?.setCursor({line:+b.dataset.refLine-1,ch:0}),0)});
install();window.Intelligence42={current,target,definitions:defs,references:refs,scopedReferences:scopedRefs,goToDefinition:jump,findReferences:showRefs,rename,apiArgs,iconCompletion}})();