(()=>{
const $=q=>document.querySelector(q),A=window.PluginStudioAPI;
if(!A)throw new Error("Plugin tools: PluginStudioAPI unavailable");
const td=new TextDecoder();
function u16(v,o){return v.getUint16(o,true)}function u32(v,o){return v.getUint32(o,true)}
async function inflateRaw(bytes){if(typeof DecompressionStream==="undefined")throw new Error("מנוע התצוגה אינו תומך ב-Deflate מקומי.");const ds=new DecompressionStream("deflate-raw"),w=ds.writable.getWriter();w.write(bytes);w.close();return new Uint8Array(await new Response(ds.readable).arrayBuffer())}
async function unzip(buffer){const v=new DataView(buffer),b=new Uint8Array(buffer),files={};let eocd=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--)if(u32(v,i)===0x06054b50){eocd=i;break}if(eocd<0)throw Error("הקובץ אינו ZIP תקין.");const count=u16(v,eocd+10),cd=u32(v,eocd+16);let p=cd;for(let n=0;n<count;n++){if(u32(v,p)!==0x02014b50)throw Error("Central directory פגום.");const method=u16(v,p+10),cs=u32(v,p+20),us=u32(v,p+24),nl=u16(v,p+28),xl=u16(v,p+30),cl=u16(v,p+32),lo=u32(v,p+42),name=td.decode(b.slice(p+46,p+46+nl));p+=46+nl+xl+cl;if(!name||name.endsWith("/"))continue;if(name.startsWith("/")||name.includes("../")||name.includes("\\..\\"))throw Error("נחסם נתיב ZIP לא בטוח: "+name);if(u32(v,lo)!==0x04034b50)throw Error("Local ZIP header פגום.");const lnl=u16(v,lo+26),lxl=u16(v,lo+28),start=lo+30+lnl+lxl,raw=b.slice(start,start+cs);let data;if(method===0)data=raw;else if(method===8)data=await inflateRaw(raw);else throw Error("שיטת ZIP לא נתמכת: "+method);if(us&&data.length!==us)throw Error("גודל קובץ לא תואם: "+name);files[name]=td.decode(data)}return files}
$("#importPackage").onclick=()=>$("#packageInput").click();
$("#packageInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const files=await unzip(await f.arrayBuffer());if(!files["manifest.json"])throw Error("manifest.json חייב להיות בשורש החבילה.");let m;try{m=JSON.parse(files["manifest.json"])}catch{throw Error("manifest.json אינו JSON תקין.")}if(!m.id||!m.name||!m.version||!m.entrypoint)throw Error("manifest.json חסר שדות חובה.");if(!files[m.entrypoint])throw Error("קובץ ה-entrypoint חסר בחבילה.");A.importFiles(files,m.name+" (imported)");alert("החבילה פורקה ונפתחה כפרויקט עם "+Object.keys(files).length+" קבצים.")}catch(err){alert("פתיחת החבילה נכשלה: "+err.message)}finally{e.target.value=""}};
function apiLab(){const methods=A.sdk.methods.filter(x=>!x.startsWith("network."));A.dialog("API Lab",'<div class="notice">מעבדת API מקומית. קריאות network.* חסומות.</div><div class="field"><label>API</label><input id="labApi" list="labApis" dir="ltr"></div><datalist id="labApis">'+methods.map(x=>'<option value="'+A.escapeHtml(x)+'">').join("")+'</datalist><div id="labMeta" class="notice"></div><div class="field"><label>Arguments JSON</label><textarea id="labArgs" dir="ltr" style="width:100%;height:140px;position:static;color:var(--color-on-surface)!important;-webkit-text-fill-color:initial;background:var(--color-surface)!important">{}</textarea></div><button id="labRun">הרץ</button> <button id="labClear">נקה</button><pre id="labOut" style="max-height:300px;overflow:auto"></pre>');const meta=()=>{const n=$("#labApi").value,p=A.sdk.methodPermissions?.[n]||"baseline",v=A.sdk.methodMinVersions?.[n]||"?";$("#labMeta").textContent=((window.OTZARIA_SIGNATURES||{})[n]||n+"(args)")+" · permission: "+p+" · min: "+v};$("#labApi").oninput=meta;$("#labClear").onclick=()=>$("#labOut").textContent="";$("#labRun").onclick=async()=>{const n=$("#labApi").value;if(!methods.includes(n))return $("#labOut").textContent="API לא מוכר או חסום.";let args;try{args=JSON.parse($("#labArgs").value||"{}")}catch(e){return $("#labOut").textContent="Arguments JSON שגוי: "+e.message}const started=performance.now(),req={api:n,args,time:new Date().toISOString()};$("#labOut").textContent="REQUEST\n"+JSON.stringify(req,null,2)+"\n\nRunning…";try{const res=await A.hostCall(n,args),ms=(performance.now()-started).toFixed(1);$("#labOut").textContent="REQUEST\n"+JSON.stringify(req,null,2)+"\n\nRESPONSE ("+ms+" ms)\n"+JSON.stringify(res,null,2)}catch(err){const ms=(performance.now()-started).toFixed(1);$("#labOut").textContent="REQUEST\n"+JSON.stringify(req,null,2)+"\n\nERROR ("+ms+" ms)\n"+String(err?.stack||err)}};meta()}
$("#apiLabBtn").onclick=apiLab;
window.PluginTools={unzip,apiLab};
})();