(()=>{const A=window.PluginStudioAPI,$=q=>document.querySelector(q),L=k=>window.StudioLocale54?.t?.(k)||k,K="plugin-studio-session-5-5";if(!A)return;
function modal(title,body,actions=[]){return new Promise(resolve=>{A.dialog(title,body+'<div id="ps55Actions" class="ps55Actions"></div>');const host=$("#ps55Actions");actions.forEach((a,i)=>{const b=document.createElement("button");b.textContent=a.label;b.className=a.primary?"primaryAction":"";b.onclick=()=>{$("#dlg").close();resolve(a.value)};host.appendChild(b)});$("#dlg").addEventListener("close",()=>resolve(null),{once:true})})}
const alertBox=(message,title=L("workspace"))=>modal(title,'<div class="notice">'+A.escapeHtml(message)+'</div>',[{label:L("close")||"Close",value:true,primary:true}]);
const confirmBox=(message,title=L("workspace"))=>modal(title,'<div class="notice">'+A.escapeHtml(message)+'</div>',[{label:L("no"),value:false},{label:L("yes"),value:true,primary:true}]);
function promptBox(message,value="",title=L("workspace")){return new Promise(resolve=>{A.dialog(title,'<div class="field"><label>'+A.escapeHtml(message)+'</label><input id="ps55Prompt" value="'+A.escapeHtml(value)+'"></div><div class="ps55Actions"><button id="ps55Cancel">'+L("no")+'</button><button id="ps55Ok" class="primaryAction">'+L("yes")+'</button></div>');const i=$("#ps55Prompt");i.focus();i.select();$("#ps55Cancel").onclick=()=>{$("#dlg").close();resolve(null)};$("#ps55Ok").onclick=()=>{const v=i.value;$("#dlg").close();resolve(v)};i.onkeydown=e=>{if(e.key==="Enter")$("#ps55Ok").click()}})}
function saveSession(){const cm=window.StudioCodeMirror,p=cm?.getCursor?.();const data={file:A.currentFile||null,cursor:p||null,scroll:cm?{left:cm.getScrollInfo().left,top:cm.getScrollInfo().top}:null,outline:$("#editorOutline")?.classList.contains("show")||false,zen:document.body.classList.contains("zenMode"),bottom:document.body.classList.contains("bottomCollapsed"),sdk:document.body.classList.contains("sdkHidden")};localStorage.setItem(K,JSON.stringify(data))}
function restoreSession(){let x;try{x=JSON.parse(localStorage.getItem(K)||"null")}catch{}if(!x)return;if(x.file&&A.state.files[x.file]!=null)A.openFile(x.file);setTimeout(()=>{const cm=window.StudioCodeMirror;if(x.cursor)cm?.setCursor?.(x.cursor);if(x.scroll)cm?.scrollTo?.(x.scroll.left,x.scroll.top);$("#editorOutline")?.classList.toggle("show",!!x.outline);document.body.classList.toggle("zenMode",!!x.zen);document.body.classList.toggle("bottomCollapsed",!!x.bottom);document.body.classList.toggle("sdkHidden",!!x.sdk)},450)}
function dirty(){document.body.classList.add("hasUnsavedWork");clearTimeout(dirty.t);dirty.t=setTimeout(()=>document.body.classList.remove("hasUnsavedWork"),1100)}
function init(){restoreSession();setInterval(saveSession,4000);addEventListener("beforeunload",saveSession);document.addEventListener("pluginstudio:file-opened",saveSession);setTimeout(()=>window.StudioCodeMirror?.on?.("change",dirty),500)}
init();window.Studio55={modal,alert:alertBox,confirm:confirmBox,prompt:promptBox,saveSession,restoreSession}})();