(()=>{const A=window.PluginStudioAPI;if(!A)return;const $=q=>document.querySelector(q),K="plugin-studio-workspace-v51";let state={left:220,right:240,bottom:168,leftOpen:true,rightOpen:true,bottomOpen:true,zen:false};try{state={...state,...JSON.parse(localStorage.getItem(K)||"{}")}}catch{}const save=()=>{try{localStorage.setItem(K,JSON.stringify(state))}catch{}};
const icons={explorer:"▱",search:"⌕",sdk:"◇",problems:"△",builder:"▦",test:"✓",tools:"⌘",settings:"⚙",zen:"□"};
function button(id,icon,title,fn){const b=document.createElement("button");b.id=id;b.className="activityBtn";b.textContent=icon;b.title=title;b.setAttribute("aria-label",title);b.onclick=fn;return b}
function layout(){const main=$("main"),bottom=$(".bottom");if(!main)return;document.documentElement.style.setProperty("--ps-left",state.leftOpen?state.left+"px":"0px");document.documentElement.style.setProperty("--ps-right",state.rightOpen?state.right+"px":"0px");document.documentElement.style.setProperty("--ps-bottom",state.bottomOpen?state.bottom+"px":"34px");document.body.classList.toggle("workspaceLeftHidden",!state.leftOpen);document.body.classList.toggle("workspaceRightHidden",!state.rightOpen);document.body.classList.toggle("workspaceBottomHidden",!state.bottomOpen);document.body.classList.toggle("zenMode",state.zen);bottom?.classList.toggle("panelCollapsed",!state.bottomOpen);window.StudioCodeMirror?.refresh?.();save()}
function toggle(which){state[which]=!state[which];layout()}
function activity(){if($("#activityBar"))return;const bar=document.createElement("nav");bar.id="activityBar";bar.className="activityBar";bar.setAttribute("aria-label","Workspace");bar.append(button("activityExplorer",icons.explorer,"Explorer",()=>toggle("leftOpen")),button("activitySearch",icons.search,"Search",()=>$("#projectSearch")?.click()),button("activitySdk",icons.sdk,"Otzaria SDK",()=>toggle("rightOpen")),button("activityProblems",icons.problems,"Problems",()=>{$("#problemsTab")?.click();state.bottomOpen=true;layout()}),button("activityBuilder",icons.builder,"Visual Builder",()=>$("#visualBuilderBtn")?.click()),button("activityTest",icons.test,"Testing",()=>$("#testingStudioBtn")?.click()),button("activityTools",icons.tools,"Command Palette",()=>$("#quickOpen")?.click()));const spacer=document.createElement("span");spacer.className="activitySpacer";bar.append(spacer,button("activityZen",icons.zen,"Zen mode",()=>{state.zen=!state.zen;layout()}),button("activitySettings",icons.settings,"Settings",()=>$("#studioSettingsBtn")?.click()));document.body.appendChild(bar)}
function command(){if($("#commandCenter"))return;const h=$("header.topbar"),brand=h?.querySelector("b");if(!h)return;const b=document.createElement("button");b.id="commandCenter";b.className="commandCenter";b.innerHTML='<span>⌕</span><span class="commandLabel">Search files, commands and symbols</span><kbd>Ctrl+K</kbd>';b.onclick=()=>$("#quickOpen")?.click();brand?.after(b)}
function splitter(cls,onmove){const s=document.createElement("div");s.className="workspaceSplitter "+cls;s.setAttribute("role","separator");s.tabIndex=0;s.onpointerdown=e=>{e.preventDefault();s.setPointerCapture?.(e.pointerId);const move=x=>onmove(x);s.onpointermove=x=>move(x);s.onpointerup=()=>{s.onpointermove=null;s.onpointerup=null;save()}};return s}
function splitters(){const main=$("main"),left=main?.querySelector("aside:first-child"),right=main?.querySelector("aside:last-child"),bottom=$(".bottom");if(!main||!left||!right||!bottom||$(".leftSplitter"))return;left.after(splitter("leftSplitter",e=>{const r=main.getBoundingClientRect();state.left=Math.max(150,Math.min(420,document.dir==="rtl"?r.right-e.clientX:e.clientX-r.left));layout()}));right.before(splitter("rightSplitter",e=>{const r=main.getBoundingClientRect();state.right=Math.max(170,Math.min(440,document.dir==="rtl"?e.clientX-r.left:r.right-e.clientX));layout()}));bottom.before(splitter("bottomSplitter",e=>{state.bottom=Math.max(90,Math.min(innerHeight*.55,innerHeight-e.clientY));state.bottomOpen=true;layout()}))}
function context(){document.addEventListener("contextmenu",e=>{const f=e.target.closest?.(".file"),t=e.target.closest?.(".tab");if(!f&&!t)return;e.preventDefault();let m=$("#workspaceContext");if(!m){m=document.createElement("div");m.id="workspaceContext";m.className="workspaceContext";document.body.appendChild(m)}const file=f?.dataset.f||t?.dataset.t;m.innerHTML='<button data-c="open">Open</button><button data-c="rename">Rename</button><button data-c="search">Find references</button><button data-c="delete">Delete</button>';m.style.left=Math.min(e.clientX,innerWidth-170)+"px";m.style.top=Math.min(e.clientY,innerHeight-160)+"px";m.classList.add("show");m.onclick=x=>{const a=x.target.dataset.c;if(a==="open")A.openFile?.(file);if(a==="rename"){A.openFile?.(file);$("#renameFile")?.click()}if(a==="search"){A.openFile?.(file);window.Intelligence42?.findReferences?.()}if(a==="delete"){A.openFile?.(file);$("#deleteFile")?.click()}m.classList.remove("show")}});document.addEventListener("click",e=>{if(!e.target.closest?.("#workspaceContext"))$("#workspaceContext")?.classList.remove("show")})}
function status(){const old=$("#status");if(!old||$("#workspaceStatus"))return;const wrap=document.createElement("div");wrap.id="workspaceStatus";wrap.className="workspaceStatus";old.parentNode.insertBefore(wrap,old);wrap.appendChild(old);const meta=document.createElement("div");meta.className="workspaceMeta";meta.innerHTML='<span id="wsFile"></span><span id="wsCursor">Ln 1, Col 1</span><span id="wsProblems">✓</span><span>OFFLINE</span>';wrap.appendChild(meta);const update=()=>{$("#wsFile").textContent=A.currentFile||"";const c=window.StudioCodeMirror,p=c?.getCursor?.();if(p)$("#wsCursor").textContent="Ln "+(p.line+1)+", Col "+(p.ch+1);const n=A.collectProblems?.()?.length||0;$("#wsProblems").textContent=n?n+" problems":"✓ No problems"};document.addEventListener("pluginstudio:file-opened",update);setInterval(update,1500);setTimeout(()=>{window.StudioCodeMirror?.on?.("cursorActivity",update);update()},300)}
function keys(){document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#quickOpen")?.click()}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==="z"){e.preventDefault();state.zen=!state.zen;layout()}if(e.key==="Escape"&&state.zen){state.zen=false;layout()}})}
function init(){activity();command();splitters();context();status();keys();layout();document.body.classList.add("workspace51")}
setTimeout(init,0);window.Workspace51={state,layout,toggle}})();